export enum RoutesKey {
  Hello = 'hello',
  Dashboard = 'dashboard',
  Setting = 'setting',
  Static = 'static',
  Announcement = 'announcement',
  Category = 'category',
  Tag = 'tag',
  Comment = 'comment',
  Disqus = 'disqus',
  DisqusThread = 'disqus-thread',
  DisqusPost = 'disqus-post',
  DisqusSync = 'disqus-sync',
  Vote = 'vote',
  Feedback = 'feedback',
  Article = 'article',
  ArticleList = 'article-list',
  ArticlePost = 'article-post',
  ArticleEdit = 'article-edit'
}
