name: Deploy Production to Cloudflare Workers

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Vite build
        run: pnpm run build

      - name: Release branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: prod
          publish_dir: ./dist

      # https://developers.cloudflare.com/workers/static-assets/migration-guides/migrate-from-pages/#serving-behavior
      # https://developers.cloudflare.com/workers/static-assets/binding/#ignoring-assets
      # https://developers.cloudflare.com/workers/ci-cd/external-cicd/github-actions/
      - name: Deploy content to Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # https://developers.cloudflare.com/workers/wrangler/commands/#deploy
          command: deploy --name=surmon-me-admin --compatibility-date="2025-06-25" --assets="./dist"
